<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Luma.Abstractions\Luma.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Luma.Runtime\Luma.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Luma.ModelLib\Luma.ModelLib.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
