<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Luma.Abstractions\Luma.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Luma.ModelLib\Luma.ModelLib.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="assets\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
